; ==========================================
; Roundcube Core & Mandatory Extensions
; ==========================================
zend_extension=opcache
extension=mbstring
extension=dom
extension=openssl
extension=session
extension=sockets
extension=intl
extension=ctype
extension=iconv
extension=fileinfo

; database
extension=mysqlnd
extension=mysqli
extension=pdo
extension=pdo_mysql
extension=pdo_pgsql
extension=pdo_sqlite

; ==========================================
; Roundcube Recommended & Optional Extensions
; ==========================================
extension=gd
extension=zip       ; Allows downloading multiple attachments as a zip file
extension=curl      ; Needed for external integrations / HTTP requests
extension=ldap      ; Needed if using LDAP for contact books
extension=xmlwriter ; Recommended for plugin compatibility

[PHP]
opcache.validate_timestamps = 0
opcache.jit = 1255
opcache.jit_buffer_size = 128M
